url: thedudewiththething.com
timezone: America/New_York
markdown: kramdown
exclude: ['Gruntfile.coffee', 'bower.json', 'package.json', 'Gemfile', 'Gemfile.lock', 'README.md']
description: >
  A place for tech projects and the like.
